### ISSUE TITLE
Use an MSIX installer.

### ISSUE THREAD

**Issue by Poopooracoocoo** [ProtonVPN/win-app#12]

**Comment by kaplun** [comment]
Hi! What would be your use case? In which way an MSIX installer would be better than the current installer that is being used?

**Comment by Poopooracoocoo** [comment]
>In which way an MSIX installer would be better than the current installer that is being used?

i don't really know :/ it's just the newer packaging format. i like the clean install and uninstall and the Settings integration. there's not really a benefit of having an msix installer...

**Comment by Poopooracoocoo** [comment]
@behroozbc what do you think?

**Comment by System0x40** [comment]
A lot of people despise the existence of all the UWP, WinRT, MSIX and all the other BS Microsoft started since 8 and you suggest dropping a Win32/.NET Framework installer in favour of that?

**Comment by Poopooracoocoo** [comment]
I hardly even remember making this issue, but you're not pointing out any disadvantages with MSIX here. Sure, people hate UWP and WinRT. It was a mess for both users and developers. What does MSIX have to do with that other than being a newer technology?

**Comment by soredake** [comment]
> In which way an MSIX installer would be better than the current installer that is being used?

https://github.com/felixrieseberg/windows95/issues/221
https://github.com/nodejs/node/issues/25519
https://learn.microsoft.com/en-us/windows/msix/overview#key-features
