### ISSUE TITLE
Problems when using WSL

### ISSUE THREAD

**Issue by SirWindfield** [ProtonVPN/win-app#16]
I just noticed that, if I have ProtonVPN enabled on my Windows host system, and try to update my Ubuntu installation inside of WSL (`sudo apt update`), the command fails to reach the update servers. Disabling the VPN does work though.

I am not sure on how to resolve this exactly tbh and hope that someone here can help me out :)

**Comment by kaplun** [comment]
Hey sorry to see this only now. Can you contact our customer support at: https://protonvpn.com/support-form ?

**Comment by SirWindfield** [comment]
No problem! I've used the form, thanks!
