### ISSUE TITLE
Kill Switch- Page not found

### ISSUE THREAD

**Issue by KovalevArtem** [ProtonVPN/win-app#23]
![image](https://user-images.githubusercontent.com/36500228/101993156-74c39580-3cc9-11eb-9574-8c0cc2a9e200.png)
If you click "Learn more" you get here:

![image](https://user-images.githubusercontent.com/36500228/101993160-7e4cfd80-3cc9-11eb-8f9b-c3b9aa62d0f0.png)
https://protonvpn.com/support/what-is-kill-switch

Version 1.18.0

**Comment by mindaugasveblauskas** [comment]
It's already resolved.
