### ISSUE TITLE
Split Tunneling Does Not Work

### ISSUE THREAD

**Issue by fried-tantrum** [ProtonVPN/win-app#31]
ProtonVPN version: 1.21.1
Windows Version: 21H1
Windows Build: 19043.985

Currently I have three programs that should be running outside the VPN tunnel: Signal, Tor browser, and Brave. None of them work. If I run them back through the tunnel, they work fine. Happy to provide any other details, logs, screenshots, etc needed, but I am only a moderate user so you may have to tell me how to find them in some cases.

**Comment by JulianPardo** [comment]
That there is no answer worries me, what is the support that one has for a paid app?

**Comment by fried-tantrum** [comment]
> 
> 
> That there is no answer worries me, what is the support that one has for a paid app?

I reached out directly to support and they are in the process of helping me troubleshoot it. I'll update if/when it gets resolved one way or another.

**Comment by fried-tantrum** [comment]
Support helped me find a solution. I had to uninstall ProtonVPN, turn off my antivirus and firewall, reinstall ProtonVPN, and then I could safely turn my AV/Firewall back on. It seems to be working now.
