### ISSUE TITLE
unable access to clients-shared.git at https://gitlab.protontech.ch

### ISSUE THREAD

**Issue by NimaEagle** [ProtonVPN/win-app#35]
`$ git submodule update --init`
Cloning into 'C:/windows_projects/ProtonVPN/win-app/src/ProtonVPN.LocalAgent'...
fatal: unable to access 'https://gitlab.protontech.ch/ProtonVPN/development/clients-shared.git/': Failed to connect to gitlab.protontech.ch port 443: Timed out
fatal: clone of 'https://gitlab.protontech.ch/ProtonVPN/development/clients-shared.git' into submodule path 'C:/windows_projects/ProtonVPN/win-app/src/ProtonVPN.LocalAgent' failed
Failed to clone 'src/ProtonVPN.LocalAgent'. Retry scheduled
Cloning into 'C:/windows_projects/ProtonVPN/win-app/src/ProtonVPN.LocalAgent'...
fatal: unable to access 'https://gitlab.protontech.ch/ProtonVPN/development/clients-shared.git/': Failed to connect to gitlab.protontech.ch port 443: Timed out
fatal: clone of 'https://gitlab.protontech.ch/ProtonVPN/development/clients-shared.git' into submodule path 'C:/windows_projects/ProtonVPN/win-app/src/ProtonVPN.LocalAgent' failed
Failed to clone 'src/ProtonVPN.LocalAgent' a second time, aborting

_I've also pinged to https://gitlab.protontech.ch/ProtonVPN/development/clients-shared.git but seems its down :(_

**Comment by mindaugasveblauskas** [comment]
Hello, the issue was fixed and is already available on the master branch. Commit reference - https://github.com/ProtonVPN/win-app/commit/4614ada39b2b6e3a0ba140d20d4fda9e5a144ed7
