### ISSUE TITLE
Is there any timeline for supporting Stealth protocol for windows app?

### ISSUE THREAD

**Issue by jesspinklet** [ProtonVPN/win-app#64]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

**Comment by FaridZelli** [comment]
ProtonVPN's Stealth protocol is one of the very few reliable connection methods for users in Iran, it's crucial to implement it as soon as possible. Getting an ETA for the first early access build can help us out a lot.

**Comment by treexe** [comment]
please bring stealth protocol to win or linux platform, we're suffering here

**Comment by EhsanFox** [comment]
If there can be any branch that contains Stealth protocol, stable or not, would be much better, I mean you guys can also test the Protocol and free beta users and feedback, and basically, a handout to Iranian people at this moment.

**Comment by MahdiPixel** [comment]
Please add the **Stealth Protocol** to the **desktop** version of the app. 🙏🙏❤

**Comment by GlassesPi** [comment]
Any updates on Stealth protocol support?

**Comment by rbarinov** [comment]
Vote for this feature!

**Comment by navidei** [comment]
+1

**Comment by Tnology** [comment]
Please bring the Stealth protocol to either Linux, Windows, or both!

**Comment by creativefctr** [comment]
+1

**Comment by Zabrhn** [comment]
We are in desperate need of this in Iran!
Plz hurry up, tnx.

**Comment by MiLaDTechS** [comment]
+1

**Comment by whoman** [comment]
+1

**Comment by mortazaamoo** [comment]
+1

**Comment by LRGuess** [comment]
PLEASE STEALTH I NEED REALLY BAD TO GET ACCESS TO SITES

**Comment by intexcor** [comment]
В чем проблем добавить протокол?

**Comment by Voi8z** [comment]
We really need stealth mode in linux

**Comment by Saman-Izadi** [comment]
they forgor 💀

**Comment by ampr64** [comment]
Read on a Reddit post somewhere by the ProtonVPN guys themselves that they were adding this feature this summer. Any truth to this?

**Comment by LRGuess** [comment]
This is now supported in the latest update, 3.3.0! Enjoy!

**Comment by LRGuess** [comment]
@jesspinklet can be closed

**Comment by centerepic** [comment]
Still not on linux...?

**Comment by kylekatarnls** [comment]
https://protonvpn.com/support/wireguard-linux

**Comment by jesspinklet** [comment]
Too late....
