### ISSUE TITLE
The older version of ProtonVpn cannot be removed

### ISSUE THREAD

**Issue by thisiscyiran** [ProtonVPN/win-app#65]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Hello there, I would like to uninstall and re-install the ProtonVpn app But 
I keep facing this error:

![Screenshot 2022-10-22 161224](https://user-images.githubusercontent.com/58443122/197340056-192a6a3f-c41c-4ad2-a241-dc6ac5695f49.png)
I tried to find the `ProtonVPN_win_v2.0.6.msi` in my memory but I could not find it anywhere in my memory.

And when I try to install the app  again I get this error:
![Screenshot 2022-10-22 161736](https://user-images.githubusercontent.com/58443122/197340164-79e89aa6-b159-442d-a30b-ca18a32dbab6.png)

**Comment by thisiscyiran** [comment]
try uninstalling and reinstalling the app with this tool: https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed.

**Comment by Xii-Nyth** [comment]
Thanks same issue here
